#!/usr/bin/env bash
# =============================================================================
# 01_build_gcc_prereqs.sh
#
# GCC build-time prerequisites: GMP, MPFR, MPC, ISL.
#
# WHY WE USE ALPINE BINARY PACKAGES INSTEAD OF BUILDING FROM SOURCE:
#   GMP/MPFR/MPC are only needed on the *host* side — they get statically
#   linked into the final gcc/g++ binaries and are not present in the produced
#   arm-none-eabi toolchain at all.  Building them from source on Alpine fails
#   because GMP's configure compiles + *runs* small test programs to verify
#   long-long arithmetic; those binaries fail to execute under Alpine's runtime
#   loader when built from a raw configure environment (missing RPATH, no
#   LD_LIBRARY_PATH, libgcc_s search-path issues).
#
#   Alpine ships correct musl-linked gmp-dev / mpfr-dev / mpc1-dev / isl-dev
#   packages — the exact same libraries GCC's build system needs.  We install
#   those with apk and point GCC's configure at /usr.
# =============================================================================
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/config.env"

section "01  GCC Prerequisites — GMP / MPFR / MPC / ISL  (Alpine packages)"

# ---- Must be able to run apk -------------------------------------------------
if ! command -v apk &>/dev/null; then
    log_error "apk not found — this script requires Alpine Linux."
fi

# ---- Install dev packages ----------------------------------------------------
APK_PREREQS=(
    gmp-dev         # GNU Multiple Precision Arithmetic
    mpfr-dev        # Multiple-precision floating point
    mpc1-dev        # Multiple-precision complex arithmetic
    isl-dev         # Integer Set Library (Graphite loop optimiser in GCC)
    zlib-dev        # needed by GCC's LTO plugin
    libffi-dev      # needed by GCC's go front-end (harmless if go not built)
)

log_info "Installing GCC prerequisite dev packages via apk ..."
if [[ "$EUID" -ne 0 ]]; then
    sudo apk add --no-cache "${APK_PREREQS[@]}" 2>&1 | tee -a "${AP_LOG}" >&2
else
    apk add --no-cache "${APK_PREREQS[@]}" 2>&1 | tee -a "${AP_LOG}" >&2
fi

# ---- Verify headers and libraries are present --------------------------------
log_info "Verifying prerequisite libraries ..."
FAILED=0
for header in gmp.h mpfr.h mpc.h isl/isl_version.h; do
    found=$(find /usr/include -name "$(basename "${header}")" 2>/dev/null | head -1)
    if [[ -n "${found}" ]]; then
        log_ok "  header: ${found}"
    else
        log_warn "  MISSING header: ${header}"
        FAILED=$((FAILED + 1))
    fi
done

for lib in libgmp libmpfr libmpc libisl; do
    found=$(find /usr/lib -name "${lib}.so*" -o -name "${lib}.a" 2>/dev/null | head -1)
    if [[ -n "${found}" ]]; then
        log_ok "  library: ${found}"
    else
        log_warn "  MISSING library: ${lib}"
        FAILED=$((FAILED + 1))
    fi
done

[[ "${FAILED}" -eq 0 ]] || log_error "${FAILED} prerequisite(s) missing after apk install."

# ---- Export paths for scripts 02 and 03 --------------------------------------
# These variables tell GCC's configure where to find GMP/MPFR/MPC/ISL.
# /usr is where apk installs them on Alpine.
export GCC_PREREQ_PREFIX=/usr

# Write a small env-file so 02 and 03 can source it even in fresh shells
cat > "${AP_PREFIX}/prereqs.env" << EOF
# Auto-generated by 01_build_gcc_prereqs.sh
export GCC_PREREQ_PREFIX=/usr
export CPPFLAGS="-I/usr/include"
export LDFLAGS="-L/usr/lib"
export PKG_CONFIG_PATH="/usr/lib/pkgconfig:${AP_PREFIX}/lib/pkgconfig"
EOF
log_info "Wrote ${AP_PREFIX}/prereqs.env"

log_ok "GCC prerequisites ready.  Proceed with 02_build_binutils.sh"
